### ISSUE TITLE
how get store app url?

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/IntuneDocs.zh-cn#22]
Please provide information for get store app url.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5ef11620-62ae-576d-2816-f69a754842ea
* Version Independent ID: db306ce4-3d75-023b-b267-6151c9df5a8d
* Content: [将 Microsoft Store 应用添加到 Microsoft Intune](https://docs.microsoft.com/zh-cn/intune/apps/store-apps-windows#feedback)
* Content Source: [intune/apps/store-apps-windows.md](https://github.com/MicrosoftDocs/IntuneDocs.zh-cn/blob/live/intune/apps/store-apps-windows.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by srvbpigh** [comment]
Hello, @goxia
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @goxia

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/IntuneDocs/issues/3217

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
